backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads" 
public_folder: "/images/uploads" 

collections:
  -name: "product"
   label: "Product"
   folder: "products"
   create: "true"
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
   fields:
    - { label: "Products", name: "products", widget: "hidden", default: "product" }
    - { label: "Categories", name: "categories", widget: "list", allow_add: true, field: {label: "Category", name: "category", widget: "string" }}
    - { label: "Price", name: "price", widget: "number" }
    - { label: "Name", name: "name", widget: "string" }
    - { label: "Image", name: "image", widget: "image" }
    - { label: "Description", name: "description", widget: "text" }
    - { label: "Inventory", name: "currentIventory", widget: "number" }
    - { label: "Brand", name: "brand", widget: "string" }

